'use client';
import {useEffect,useState} from 'react';
import {ShieldCheck,RefreshCw} from 'lucide-react';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogCancel} from '@/components/ui/alert-dialog';
import {toast} from 'sonner';
import {Data,uid} from '@/lib/jaga';
import {cloud,CloudSession,dataFingerprint,saveCloud,legacyData,hasLocalData,mergeLegacy,Version} from '@/lib/cloud';
export type AccountProps={cloudUser?:string;initialData?:Data;onLogout?:()=>Promise<void>};
export function CloudAccount({render}:{render:(props:AccountProps)=>React.ReactNode}){
  const [session,setSession]=useState<CloudSession|null>(null),[data,setData]=useState<Data|null>(null),[local,setLocal]=useState<Data|null>(null),[mode,setMode]=useState('loading'),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[recover,setRecover]=useState(false),[transfer,setTransfer]=useState(false);
  async function load(){setError('');setBusy(true);try{
    const s=await cloud<CloudSession&{configured?:boolean}>('auth/me');
    if(s.configured===false){setMode('local');return;}
    setSession(s);if(!s.user){setMode('login');return;}
    const value=await cloud<{data:Data}>('state');setData(value.data);
    try{const old=await legacyData();let transferred=false;try{transferred=localStorage.getItem('jaga-migrated:'+s.user.username)===await dataFingerprint(old);}catch{}setLocal(hasLocalData(old)&&!transferred?old:null);}catch{setLocal(null);}
    setMode('cloud');
  }catch(e){setError((e as Error).message);setMode('error');}finally{setBusy(false);}}
  useEffect(()=>{void load();},[]);
  async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await cloud(recover?'auth/recover':session?.initialized?'auth/login':'auth/setup','POST',{username,password});setPassword('');setRecover(false);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function migrate(){if(!local||!data)return;setBusy(true);setError('');try{const latest=(await cloud<{data:Data}>('state')).data;const combined=mergeLegacy(latest,local);const next={...combined,revision:latest.revision+1,audit:[...combined.audit,{id:uid(),at:new Date().toISOString(),action:'migrate_device',before:null,after:{events:local.events.length},reason:'Pemindahan catatan perangkat'}]};setData(await saveCloud(next,latest.revision));try{localStorage.setItem('jaga-migrated:'+session!.user!.username,await dataFingerprint(local));}catch{}setLocal(null);setTransfer(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  const backupLocal=()=>{if(!local)return;const url=URL.createObjectURL(new Blob([JSON.stringify({format:'jaga-backup',data:local},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='jaga-catatan-perangkat.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  if(mode==='local')return render({});
  if(mode==='cloud'&&session?.user&&data)return <>{local&&<div className="migration-banner"><span>Ada {local.events.length} kegiatan lama di perangkat ini.</span><button className="secondary" onClick={backupLocal}>Unduh cadangan lama</button><button className="primary" onClick={()=>setTransfer(true)}>Pindahkan ke akun</button>{error&&<p className="error">{error}</p>}</div>}{render({cloudUser:session.user.username,initialData:data,onLogout:async()=>{await cloud('auth/logout','POST',{});setData(null);setSession(null);await load();}})}<AlertDialog open={transfer} onOpenChange={setTransfer}><AlertDialogContent><AlertDialogTitle>Pindahkan catatan perangkat?</AlertDialogTitle><AlertDialogDescription>Catatan akan digabung dengan akun {session.user.username}. Data yang berbeda dengan ID sama tidak ditimpa. Salinan lama di perangkat tetap disimpan.</AlertDialogDescription><div className="button-row"><button className="secondary" onClick={backupLocal}>Unduh cadangan</button><AlertDialogCancel>Kembali</AlertDialogCancel><button className="primary" disabled={busy} onClick={migrate}>{busy?'Memindahkan…':'Pindahkan'}</button></div>{error&&<p className="error">{error}</p>}</AlertDialogContent></AlertDialog></>;
  return <main className="account-screen"><section className="panel account-panel"><span className="account-logo"><ShieldCheck size={30}/></span><h1>{mode==='loading'?'Membuka Jaga':mode==='error'?'Koneksi belum tersedia':recover?'Pulihkan akses akun':session?.initialized?'Masuk ke Jaga':'Buat akun Jaga'}</h1>{mode==='login'&&<><p className="muted">{recover?'Buat password baru tanpa menghapus catatan.':session?.initialized?'Catatan yang sama di setiap perangkat.':'Pilih username dan password untuk catatan pribadi lo.'}</p>{(!session?.initialized||recover)&&!session?.ownerVerified?<><p>Masuk melalui akun ChatGPT pemilik untuk {recover?'memulihkan akses':'membuat akun pertama'}.</p><a className="primary" href={session?.setupSignIn||'/signin-with-chatgpt?return_to=/'} target="_top">Verifikasi pemilik</a></>:<form className="event-form" onSubmit={login}><label>Username<input autoComplete="username" required minLength={3} maxLength={40} pattern="[a-zA-Z0-9_.-]+" value={username} onChange={e=>setUsername(e.target.value)}/></label><label>Password<input type="password" autoComplete={!session?.initialized||recover?'new-password':'current-password'} required minLength={!session?.initialized||recover?10:1} maxLength={256} value={password} onChange={e=>setPassword(e.target.value)}/></label>{(!session?.initialized||recover)&&<small>Minimal 10 karakter. Pilih password yang mudah lo ingat.</small>}<button type="submit" className="primary" disabled={busy}>{busy?'Memproses…':recover?'Simpan password baru':session?.initialized?'Masuk':'Buat akun'}</button></form>}{session?.initialized&&<button className="text-button" onClick={()=>{setRecover(!recover);setError('');setPassword('');}}>{recover?'Kembali ke login':'Lupa password?'}</button>}</>}{error&&<p className="error" role="alert">{error}</p>}{mode==='error'&&<><p>Catatan tidak dihapus saat server tidak merespons.</p><button className="primary" disabled={busy} onClick={load}><RefreshCw size={17}/>Coba lagi</button></>}{mode==='loading'&&<p className="muted">Memeriksa akun dan catatan…</p>}</section></main>;
}
export function CloudTools({data,onRestore,onLogout,busy}:{data:Data;onRestore:(data:Data)=>void;onLogout?:()=>Promise<void>;busy:boolean}){
  const [versions,setVersions]=useState<Version[]>([]),[chosen,setChosen]=useState<Version|null>(null),[working,setWorking]=useState(false);
  async function refresh(){try{setVersions((await cloud<{versions:Version[]}>('versions')).versions);}catch(e){toast.error((e as Error).message);}}
  return <section className="panel record-panel"><h3>Akun & versi pemulihan</h3><p>Perubahan tersimpan di MongoDB. Versi sebelum perubahan dapat dipulihkan. Unduh JSON ke tempat terpisah sebagai cadangan tambahan.</p><div className="button-row"><button className="secondary" disabled={busy||working} onClick={refresh}>Lihat versi sebelumnya</button><button className="secondary" disabled={busy||working} onClick={async()=>{try{await onLogout?.();}catch(e){toast.error((e as Error).message);}}}>Keluar akun</button></div>{versions.map(v=><div className="audit" key={v.revision}><span>Versi {v.revision} · {v.events} kegiatan · {v.people} rekan</span><small>{new Intl.DateTimeFormat('id-ID',{timeZone:'Asia/Jakarta',dateStyle:'medium',timeStyle:'short'}).format(new Date(v.savedAt))}</small><button className="text-button" disabled={busy||working} onClick={()=>setChosen(v)}>Pulihkan</button></div>)}<AlertDialog open={!!chosen} onOpenChange={o=>{if(!o)setChosen(null)}}><AlertDialogContent><AlertDialogTitle>Pulihkan versi {chosen?.revision}?</AlertDialogTitle><AlertDialogDescription>Versi saat ini disimpan dahulu, kemudian versi pilihan menjadi catatan aktif. Pemulihan ini bisa dibalik melalui versi sebelumnya.</AlertDialogDescription><div className="button-row"><AlertDialogCancel>Kembali</AlertDialogCancel><button className="primary" disabled={busy||working} onClick={async()=>{setWorking(true);try{const result=await cloud<{data:Data}>('versions/restore','POST',{revision:chosen?.revision,expectedRevision:data.revision});onRestore(result.data);setChosen(null);toast.success('Versi dipulihkan');await refresh();}catch(e){toast.error((e as Error).message);}finally{setWorking(false);}}}>Pulihkan versi</button></div></AlertDialogContent></AlertDialog></section>;
}
