'use client';
import {useEffect,useState} from 'react';
import {ShieldCheck,RefreshCw} from 'lucide-react';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogCancel} from '@/components/ui/alert-dialog';
import {toast} from 'sonner';
import {readSnapshot,rememberSnapshot,clearSnapshot,updateSnapshot,Snapshot} from '@/lib/offline';
import {Data,uid} from '@/lib/jaga';
import {Profile,emptyProfile} from '@/lib/profile';
import {cloud,CloudSession,dataFingerprint,saveCloud,legacyData,hasLocalData,mergeLegacy,Version} from '@/lib/cloud';
export type AccountProps={cloudUser?:string;initialData?:Data;profile?:Profile;onProfileChange?:(profile:Profile)=>void;readOnly?:boolean;onLogout?:()=>Promise<void>};
export function CloudAccount({render}:{render:(props:AccountProps)=>React.ReactNode}){
  const [session,setSession]=useState<CloudSession|null>(null),[data,setData]=useState<Data|null>(null),[local,setLocal]=useState<Data|null>(null),[mode,setMode]=useState('loading'),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[recover,setRecover]=useState(false),[register,setRegister]=useState(false),[recoveryInput,setRecoveryInput]=useState(''),[recoveryCode,setRecoveryCode]=useState(''),[transfer,setTransfer]=useState(false),[snapshot,setSnapshot]=useState<Snapshot|null>(null);
  async function load(){setError('');setBusy(true);try{
    const s=await cloud<CloudSession&{configured?:boolean}>('auth/me');
    if(s.configured===false){setMode('local');return;}
    setSession(s);if(!s.user){await clearSnapshot();setSnapshot(null);setMode('login');return;}
    const previous=await readSnapshot();if(previous&&previous.username!==s.user.username)await clearSnapshot();
    const value=await cloud<{data:Data}>('state');setData(value.data);await rememberSnapshot(s.user.username,value.data,s.user.profile??emptyProfile());setSnapshot(null);
    try{const old=await legacyData();let transferred=false;try{transferred=localStorage.getItem('jaga-migrated:'+s.user.username)===await dataFingerprint(old);}catch{}setLocal(hasLocalData(old)&&!transferred?old:null);}catch{setLocal(null);}
    setMode('cloud');
  }catch(e){const cached=await readSnapshot();if(cached&&(!(e as {status?:number}).status||(e as {status?:number}).status===503)){setSnapshot(cached);setMode('offline');}else{if((e as {status?:number}).status===401)await clearSnapshot();setError((e as Error).message);setMode('error');}}finally{setBusy(false);}}
  useEffect(()=>{void load();},[]);
  useEffect(()=>{const reconnect=()=>{if(mode==='offline'||mode==='error')void load();};window.addEventListener('online',reconnect);return()=>window.removeEventListener('online',reconnect);},[mode]);
  useEffect(()=>{window.dispatchEvent(new CustomEvent('jaga-editing',{detail:{source:'account',blocked:busy||!!password||!!recoveryInput||!!recoveryCode||transfer}}));return()=>{window.dispatchEvent(new CustomEvent('jaga-editing',{detail:{source:'account',blocked:false}}));};},[busy,password,recoveryInput,recoveryCode,transfer]);
  async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const result=await cloud<{recoveryCode?:string}>(recover?'auth/recover':register?'auth/register':'auth/login','POST',{username,password,recoveryCode:recoveryInput.trim()});setPassword('');setRecoveryInput('');setRecover(false);setRegister(false);if(result.recoveryCode)setRecoveryCode(result.recoveryCode);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function migrate(){if(!local||!data)return;setBusy(true);setError('');try{const latest=(await cloud<{data:Data}>('state')).data;const combined=mergeLegacy(latest,local);const next={...combined,revision:latest.revision+1,audit:[...combined.audit,{id:uid(),at:new Date().toISOString(),action:'migrate_device',before:null,after:{events:local.events.length},reason:'Pemindahan catatan perangkat'}]};setData(await saveCloud(next,latest.revision));try{localStorage.setItem('jaga-migrated:'+session!.user!.username,await dataFingerprint(local));}catch{}setLocal(null);setTransfer(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  const backupLocal=()=>{if(!local)return;const url=URL.createObjectURL(new Blob([JSON.stringify({format:'jaga-backup',data:local},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='jaga-catatan-perangkat.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  if(recoveryCode)return <main className="account-screen"><section className="panel account-panel"><RecoveryCard code={recoveryCode} onDone={()=>setRecoveryCode('')}/></section></main>;
  if(mode==='offline'&&snapshot)return <><div className="offline-banner" role="status"><div><strong>Mode baca · catatan terakhir</strong><span>Akun {snapshot.username} · Disimpan {new Intl.DateTimeFormat('id-ID',{timeZone:'Asia/Jakarta',dateStyle:'medium',timeStyle:'short'}).format(new Date(snapshot.savedAt))} WIB. Sambungkan internet untuk menyimpan perubahan.</span></div><button className="secondary" disabled={busy} onClick={load}><RefreshCw size={16}/>Coba hubungkan</button></div>{render({cloudUser:snapshot.username,initialData:snapshot.data,profile:snapshot.profile,readOnly:true})}</>;
  if(mode==='local')return render({});
  if(mode==='cloud'&&session?.user&&data)return <>{local&&<div className="migration-banner"><span>Ada {local.events.length} kegiatan lama di perangkat ini.</span><button className="secondary" onClick={backupLocal}>Unduh cadangan lama</button><button className="primary" onClick={()=>setTransfer(true)}>Pindahkan ke akun</button>{error&&<p className="error">{error}</p>}</div>}{render({cloudUser:session.user.username,initialData:data,profile:session.user.profile,onProfileChange:(profile)=>setSession(current=>current?.user?{...current,user:{...current.user,profile}}:current),onLogout:async()=>{await cloud('auth/logout','POST',{});await clearSnapshot();setSnapshot(null);setData(null);setSession(null);await load();}})}<AlertDialog open={transfer} onOpenChange={setTransfer}><AlertDialogContent><AlertDialogTitle>Pindahkan catatan perangkat?</AlertDialogTitle><AlertDialogDescription>Catatan akan digabung dengan akun {session.user.username}. Data yang berbeda dengan ID sama tidak ditimpa. Salinan lama di perangkat tetap disimpan.</AlertDialogDescription><div className="button-row"><button className="secondary" onClick={backupLocal}>Unduh cadangan</button><AlertDialogCancel>Kembali</AlertDialogCancel><button className="primary" disabled={busy} onClick={migrate}>{busy?'Memindahkan…':'Pindahkan'}</button></div>{error&&<p className="error">{error}</p>}</AlertDialogContent></AlertDialog></>;
  return <main className="account-screen"><section className="panel account-panel"><span className="account-logo"><ShieldCheck size={30}/></span><h1>{mode==='loading'?'Membuka Jaga':mode==='error'?'Koneksi belum tersedia':recover?'Pulihkan akses akun':register?'Buat akun Jaga':'Masuk ke Jaga'}</h1>{mode==='login'&&<><p className="muted">{recover?'Gunakan kode pemulihan untuk membuat password baru. Catatan tetap tersimpan.':register?'Pilih username dan password. Setiap akun memiliki catatan sendiri.':'Catatan yang sama di setiap perangkat, dengan akun lo sendiri.'}</p><form className="event-form" onSubmit={login}><label>Username<input autoComplete="username" required minLength={3} maxLength={40} pattern="[a-zA-Z0-9_.-]+" value={username} onChange={e=>setUsername(e.target.value)}/></label>{recover&&<label>Kode pemulihan<input autoComplete="off" required value={recoveryInput} onChange={e=>setRecoveryInput(e.target.value)}/></label>}<label>{recover?'Password baru':'Password'}<input type="password" autoComplete={register||recover?'new-password':'current-password'} required minLength={register||recover?10:1} maxLength={256} value={password} onChange={e=>setPassword(e.target.value)}/></label>{(register||recover)&&<small>Minimal 10 karakter. Simpan kode pemulihan setelah berhasil.</small>}<button type="submit" className="primary" disabled={busy}>{busy?'Memproses…':recover?'Simpan password baru':register?'Buat akun':'Masuk'}</button></form><div className="button-row"><button className="text-button" disabled={busy} onClick={()=>{setRegister(recover?false:!register);setRecover(false);setError('');setPassword('');}}>{register||recover?'Sudah punya akun? Masuk':'Belum punya akun? Daftar'}</button>{!register&&!recover&&<button className="text-button" disabled={busy} onClick={()=>{setRecover(true);setError('');setPassword('');}}>Lupa password?</button>}</div></>}{error&&<p className="error" role="alert">{error}</p>}{mode==='error'&&<><p>Catatan tidak dihapus saat server tidak merespons.</p><button className="primary" disabled={busy} onClick={load}><RefreshCw size={17}/>Coba lagi</button></>}{mode==='loading'&&<p className="muted">Memeriksa akun dan catatan…</p>}</section></main>;

}
export function CloudTools({data,onRestore,onLogout,busy}:{data:Data;onRestore:(data:Data)=>void;onLogout?:()=>Promise<void>;busy:boolean}){
  const [recoveryCode,setRecoveryCode]=useState(''),[password,setPassword]=useState('');
  const [versions,setVersions]=useState<Version[]>([]),[chosen,setChosen]=useState<Version|null>(null),[working,setWorking]=useState(false);
  useEffect(()=>{window.dispatchEvent(new CustomEvent('jaga-editing',{detail:{source:'tools',blocked:working||!!password||!!recoveryCode||!!chosen}}));return()=>{window.dispatchEvent(new CustomEvent('jaga-editing',{detail:{source:'tools',blocked:false}}));};},[working,password,recoveryCode,chosen]);
  async function refresh(){try{setVersions((await cloud<{versions:Version[]}>('versions')).versions);}catch(e){toast.error((e as Error).message);}}
  return <section className="panel record-panel"><h3>Akun & versi pemulihan</h3><p>Perubahan tersimpan di MongoDB. Versi sebelum perubahan dapat dipulihkan. Unduh JSON ke tempat terpisah sebagai cadangan tambahan.</p><div className="button-row"><button className="secondary" disabled={busy||working} onClick={refresh}>Lihat versi sebelumnya</button><button className="secondary" disabled={busy||working} onClick={async()=>{try{await onLogout?.();}catch(e){toast.error((e as Error).message);}}}>Keluar akun</button></div><form className="event-form recovery-form" onSubmit={async e=>{e.preventDefault();setWorking(true);try{const result=await cloud<{recoveryCode:string}>('auth/recovery-key','POST',{password});setPassword('');setRecoveryCode(result.recoveryCode);}catch(e){toast.error((e as Error).message);}finally{setWorking(false);}}}><label>Password saat ini<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="secondary" disabled={busy||working}>Buat kode pemulihan baru</button><small>Kode lama diganti. Simpan kode baru untuk berjaga-jaga jika lupa password.</small></form>{recoveryCode&&<RecoveryCard code={recoveryCode} onDone={()=>setRecoveryCode('')}/>} {versions.map(v=><div className="audit" key={v.revision}><span>Versi {v.revision} · {v.events} kegiatan · {v.people} rekan</span><small>{new Intl.DateTimeFormat('id-ID',{timeZone:'Asia/Jakarta',dateStyle:'medium',timeStyle:'short'}).format(new Date(v.savedAt))}</small><button className="text-button" disabled={busy||working} onClick={()=>setChosen(v)}>Pulihkan</button></div>)}<AlertDialog open={!!chosen} onOpenChange={o=>{if(!o)setChosen(null)}}><AlertDialogContent><AlertDialogTitle>Pulihkan versi {chosen?.revision}?</AlertDialogTitle><AlertDialogDescription>Versi saat ini disimpan dahulu, kemudian versi pilihan menjadi catatan aktif. Pemulihan ini bisa dibalik melalui versi sebelumnya.</AlertDialogDescription><div className="button-row"><AlertDialogCancel>Kembali</AlertDialogCancel><button className="primary" disabled={busy||working} onClick={async()=>{setWorking(true);try{const result=await cloud<{data:Data}>('versions/restore','POST',{revision:chosen?.revision,expectedRevision:data.revision});await updateSnapshot(result.data);onRestore(result.data);setChosen(null);toast.success('Versi dipulihkan');await refresh();}catch(e){toast.error((e as Error).message);}finally{setWorking(false);}}}>Pulihkan versi</button></div></AlertDialogContent></AlertDialog></section>;
}

function RecoveryCard({code,onDone}:{code:string;onDone:()=>void}){
  const [saved,setSaved]=useState(false);
  function download(){const url=URL.createObjectURL(new Blob(['Kode pemulihan Jaga\n'+code+'\n\nSimpan di tempat aman. Kode ini dapat mengganti password akun.'],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='jaga-kode-pemulihan.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  return <section className="recovery-card"><h2>Simpan kode pemulihan</h2><p>Kode ini hanya ditampilkan sekarang. Gunakan untuk memulihkan akun jika lupa password. Jangan bagikan ke orang lain.</p><code className="recovery-code">{code}</code><button className="secondary" onClick={download}>Unduh kode</button><label className="recovery-check"><input type="checkbox" checked={saved} onChange={e=>setSaved(e.target.checked)}/>Saya sudah menyimpan kode ini</label><button className="primary" disabled={!saved} onClick={onDone}>Lanjut ke catatan</button></section>;
}
