export type Person = {id:string;name:string;team:string;archived:boolean};
export type Event = {id:string;type:'swap'|'overtime';personId:string;direction:'give'|'receive';date:string;shift:'day'|'night';start:string;end:string;status:'planned'|'realized'|'cancelled';reason:string;notes:string;created:string;revision:number};
export type Audit = {id:string;at:string;action:string;before:unknown;after:unknown;reason:string};
export type Data = {schema:1;revision:number;anchor:string;people:Person[];events:Event[];confirmations:Record<string,'worked'|'absent'>;audit:Audit[]};
export const emptyData=():Data=>({schema:1,revision:0,anchor:'2026-10-12',people:[],events:[],confirmations:{},audit:[]});
export const phases=['P1','P2','M1','M2','L1','L2'];
export const names=['Pagi pertama','Pagi kedua','Malam pertama','Malam kedua','Libur pertama','Libur kedua'];
export const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jakarta',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export function validDate(s:string){return /^\d{4}-\d{2}-\d{2}$/.test(s)&&!isNaN(Date.parse(s))&&new Date(s+'T00:00:00Z').toISOString().slice(0,10)===s;}
export const addDays=(s:string,n:number)=>new Date(Date.parse(s+'T00:00:00Z')+n*86400000).toISOString().slice(0,10);
export function phase(date:string,anchor:string){const n=Math.round((Date.parse(date+'T00:00:00Z')-Date.parse(anchor+'T00:00:00Z'))/86400000);return ((n%6)+6)%6;}
export function interval(date:string,kind:'day'|'night'){return {start:date+(kind==='day'?'T08:00:00+07:00':'T20:00:00+07:00'),end:(kind==='day'?date:addDays(date,1))+(kind==='day'?'T20:00:00+07:00':'T08:00:00+07:00')};}
export const ms=(s:string)=>Date.parse(s);
export const overlap=(a:{start:string;end:string},b:{start:string;end:string})=>ms(a.start)<ms(b.end)&&ms(b.start)<ms(a.end);
export const hours=(a:{start:string;end:string})=>(ms(a.end)-ms(a.start))/3600000;
export function routine(date:string,anchor:string){const p=phase(date,anchor);return p<4?{id:date,...interval(date,p<2?'day':'night'),phase:p}:null;}
export const eventStartDate=(event:{start:string})=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jakarta',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(event.start));
export const eventsStartingOn=(events:Event[],date:string)=>events.filter(e=>eventStartDate(e)===date);
export function longShiftSegments(week:string[],anchor:string){
  if(!week.length)return [];
  const first=week[0],last=week[week.length-1];
  const segments:{startDate:string;endDate:string;column:number;span:number;continuesBefore:boolean;continuesAfter:boolean}[]=[];
  for(let d=addDays(first,-1);d<=last;d=addDays(d,1)){
    if(phase(d,anchor)!==1)continue;
    const end=addDays(d,1),visibleStart=d<first?first:d,visibleEnd=end>last?last:end;
    if(visibleStart>visibleEnd)continue;
    segments.push({startDate:d,endDate:end,column:week.indexOf(visibleStart)+1,span:week.indexOf(visibleEnd)-week.indexOf(visibleStart)+1,continuesBefore:d<first,continuesAfter:end>last});
  }
  return segments;
}
export function ledger(events:Event[]){const info:Record<string,{status:string;linked?:string}>={};const queues:Record<string,Event[]>={};
for(const e of events.filter(e=>e.type==='swap'&&e.status==='realized').sort((a,b)=>ms(a.start)-ms(b.start)||ms(a.created)-ms(b.created)||a.id.localeCompare(b.id))){const q=queues[e.personId]??(queues[e.personId]=[]);if(q.length&&q[0].direction!==e.direction){const origin=q.shift()!;info[origin.id]={status:'settled',linked:e.id};info[e.id]={status:'repayment',linked:origin.id};}else{q.push(e);info[e.id]={status:e.direction==='give'?'receivable':'payable'};}}
const balances:Record<string,number>={};for(const [id,q] of Object.entries(queues))balances[id]=q.reduce((n,e)=>n+(e.direction==='give'?1:-1),0);return {info,balances};}
export function workIntervals(data:Data,from:string,to:string,actual=false){const out:{start:string;end:string;label:string;eventId?:string}[]=[];for(let d=addDays(from,-1);d<=to;d=addDays(d,1)){const r=routine(d,data.anchor);if(r&&!data.events.some(e=>e.type==='swap'&&e.direction==='receive'&&e.status!=='cancelled'&&(!actual||e.status==='realized')&&e.date===d)&&(!actual||data.confirmations[d]==='worked'))out.push({...r,label:names[r.phase]});}for(const e of data.events)if(e.status!=='cancelled'&&(!actual||e.status==='realized')&&(e.type==='overtime'||e.direction==='give'))out.push({...e,label:e.type==='overtime'?'Lembur':'Tukar jaga',eventId:e.id});return out.filter(e=>overlap(e,{start:from+'T00:00:00+07:00',end:addDays(to,1)+'T00:00:00+07:00'}));}
export function clippedHours(items:{start:string;end:string}[],from:string,to:string){const lo=ms(from+'T00:00:00+07:00'),hi=ms(addDays(to,1)+'T00:00:00+07:00');const sorted=items.map(x=>[Math.max(lo,ms(x.start)),Math.min(hi,ms(x.end))]).filter(x=>x[1]>x[0]).sort((a,b)=>a[0]-b[0]);let total=0,end=lo;for(const [a,b] of sorted){total+=Math.max(0,b-Math.max(a,end));end=Math.max(end,b);}return total/3600000;}
export function validateEvent(e:Event,data:Data){if(!validDate(e.date)||!Number.isFinite(ms(e.start))||!Number.isFinite(ms(e.end))||ms(e.end)<=ms(e.start))throw Error('Rentang waktu tidak valid.');if(hours(e)>168)throw Error('Satu kegiatan maksimal 168 jam. Pisahkan kegiatan yang lebih panjang.');if(e.notes.length>2000)throw Error('Catatan maksimal 2.000 karakter.');if(e.status==='realized'&&ms(e.end)>Date.now())throw Error('Jaga belum selesai. Simpan sebagai rencana dahulu.');if(e.status==='cancelled')return;
const others={...data,events:data.events.filter(x=>x.id!==e.id)};
if(e.type==='swap'){if(!data.people.some(p=>p.id===e.personId))throw Error('Pilih rekan yang valid.');const full=interval(e.date,e.shift);if(ms(full.start)!==ms(e.start)||ms(full.end)!==ms(e.end))throw Error('Tukar jaga harus satu shift penuh.');if(e.direction==='receive'){const r=routine(e.date,data.anchor);if(!r||ms(r.start)!==ms(e.start))throw Error('Rekan hanya dapat menggantikan shift rutin pada tanggal ini.');if(others.events.some(x=>x.type==='swap'&&x.direction==='receive'&&x.status!=='cancelled'&&x.date===e.date))throw Error('Shift ini sudah memiliki pengganti.');if(data.confirmations[e.date]==='worked')throw Error('Hapus konfirmasi dijalani sendiri sebelum memilih pengganti.');return;}}
if(e.type==='overtime'&&(!e.reason.trim()||(e.reason==='Lainnya'&&!e.notes.trim())))throw Error('Isi alasan lembur dan keterangan jika memilih lainnya.');
const conflicts=workIntervals(others,e.date,addDays(e.date,Math.ceil(hours(e)/24)+1)).find(x=>overlap(e,x));if(conflicts)throw Error('Waktu bertabrakan dengan '+conflicts.label+'. Periksa tanggal dan jam.');}
export function validateBackup(value:unknown):Data{const d=value as Data;if(!d||d.schema!==1||!validDate(d.anchor)||!Array.isArray(d.people)||!Array.isArray(d.events)||!Array.isArray(d.audit)||!d.confirmations||!Number.isInteger(d.revision))throw Error('Format cadangan tidak dikenali.');if(d.events.length>20000||d.people.length>2000)throw Error('Cadangan terlalu besar.');const ids=new Set<string>();for(const p of d.people){if(typeof p.id!=='string'||!p.id||ids.has(p.id)||typeof p.name!=='string'||!p.name.trim()||p.name.length>100||typeof p.team!=='string'||typeof p.archived!=='boolean')throw Error('Data rekan tidak valid.');ids.add(p.id);}for(const a of d.audit){if(!a||typeof a.id!=='string'||typeof a.action!=='string'||typeof a.reason!=='string'||!Number.isFinite(ms(a.at)))throw Error('Jejak perubahan tidak valid.');}ids.clear();for(const e of d.events){if(typeof e.id!=='string'||!e.id||ids.has(e.id)||!['swap','overtime'].includes(e.type)||!['give','receive'].includes(e.direction)||!['day','night'].includes(e.shift)||!['planned','realized','cancelled'].includes(e.status)||typeof e.notes!=='string'||typeof e.reason!=='string'||!Number.isFinite(ms(e.created)))throw Error('Data kegiatan tidak valid.');ids.add(e.id);validateEvent(e,d);}for(const [date,result] of Object.entries(d.confirmations)){if(!validDate(date)||!routine(date,d.anchor)||!['worked','absent'].includes(result))throw Error('Konfirmasi shift tidak valid.');if(result==='worked'&&ms(routine(date,d.anchor)!.end)>Date.now())throw Error('Konfirmasi jaga masa depan tidak valid.');}return d;}
const dbPromise=()=>new Promise<IDBDatabase>((resolve,reject)=>{const req=indexedDB.open('jaga-personal-v1',1);req.onupgradeneeded=()=>req.result.createObjectStore('state');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});
export async function loadData(){const db=await dbPromise();return new Promise<Data>((res,rej)=>{const t=db.transaction('state','readonly');const req=t.objectStore('state').get('main');req.onsuccess=()=>res(req.result??emptyData());req.onerror=()=>rej(req.error);t.oncomplete=()=>db.close();});}
export async function saveData(next:Data,expected:number){const db=await dbPromise();return new Promise<void>((res,rej)=>{const t=db.transaction('state','readwrite');const store=t.objectStore('state');let failure:Error|undefined;const req=store.get('main');req.onsuccess=()=>{if((req.result?.revision??0)!==expected){failure=Error('Data berubah di tab lain. Muat ulang halaman sebelum menyimpan.');t.abort();}else store.put(next,'main');};t.oncomplete=()=>{db.close();res();};t.onabort=()=>{db.close();rej(failure??Error('Catatan gagal disimpan. Isian tetap tersedia.'));};t.onerror=()=>{failure=Error('Penyimpanan perangkat tidak tersedia. Buat cadangan atau periksa kapasitas.');};});}

export function uid(){if(typeof crypto.randomUUID==='function')return crypto.randomUUID();const a=crypto.getRandomValues(new Uint8Array(16));a[6]=(a[6]&15)|64;a[8]=(a[8]&63)|128;const h=Array.from(a,n=>n.toString(16).padStart(2,'0')).join('');return h.slice(0,8)+'-'+h.slice(8,12)+'-'+h.slice(12,16)+'-'+h.slice(16,20)+'-'+h.slice(20);}
